//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Resources_en_US {
            get {
                return ResourceManager.GetString("Resources_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str100 {
            get {
                return ResourceManager.GetString("str100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1000 {
            get {
                return ResourceManager.GetString("str1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   system_name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1001 {
            get {
                return ResourceManager.GetString("str1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1002 {
            get {
                return ResourceManager.GetString("str1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ct_gentype に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1003 {
            get {
                return ResourceManager.GetString("str1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sliceplan_der に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1004 {
            get {
                return ResourceManager.GetString("str1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   slice_plan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1005 {
            get {
                return ResourceManager.GetString("str1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   d_sileno に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1006 {
            get {
                return ResourceManager.GetString("str1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   d_date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1007 {
            get {
                return ResourceManager.GetString("str1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   start_time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1008 {
            get {
                return ResourceManager.GetString("str1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   workshop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1009 {
            get {
                return ResourceManager.GetString("str1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1010 {
            get {
                return ResourceManager.GetString("str1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   d_rawsts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1011 {
            get {
                return ResourceManager.GetString("str1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   d_recokind に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1012 {
            get {
                return ResourceManager.GetString("str1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   full_mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1013 {
            get {
                return ResourceManager.GetString("str1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   matsiz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1014 {
            get {
                return ResourceManager.GetString("str1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scan_mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1015 {
            get {
                return ResourceManager.GetString("str1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   speed_mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1016 {
            get {
                return ResourceManager.GetString("str1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scan_speed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1017 {
            get {
                return ResourceManager.GetString("str1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scan_time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1018 {
            get {
                return ResourceManager.GetString("str1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scan_area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1019 {
            get {
                return ResourceManager.GetString("str1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1020 {
            get {
                return ResourceManager.GetString("str1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   slice_wid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1021 {
            get {
                return ResourceManager.GetString("str1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1022 {
            get {
                return ResourceManager.GetString("str1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   det_ap_num に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1023 {
            get {
                return ResourceManager.GetString("str1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   focus に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1024 {
            get {
                return ResourceManager.GetString("str1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tube に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1025 {
            get {
                return ResourceManager.GetString("str1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   energy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1026 {
            get {
                return ResourceManager.GetString("str1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   volt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1027 {
            get {
                return ResourceManager.GetString("str1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   anpere に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1028 {
            get {
                return ResourceManager.GetString("str1028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   table_pos に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1029 {
            get {
                return ResourceManager.GetString("str1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   d_tablepos に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1030 {
            get {
                return ResourceManager.GetString("str1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tilt_angle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1031 {
            get {
                return ResourceManager.GetString("str1031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1032 {
            get {
                return ResourceManager.GetString("str1032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bhc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1033 {
            get {
                return ResourceManager.GetString("str1033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bhc_dir に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1034 {
            get {
                return ResourceManager.GetString("str1034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bhc_name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1035 {
            get {
                return ResourceManager.GetString("str1035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   zoom_dir に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1036 {
            get {
                return ResourceManager.GetString("str1036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   zoom_name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1037 {
            get {
                return ResourceManager.GetString("str1037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   zooming に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1038 {
            get {
                return ResourceManager.GetString("str1038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   zoomx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1039 {
            get {
                return ResourceManager.GetString("str1039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   zoomy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1040 {
            get {
                return ResourceManager.GetString("str1040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   zoomsize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1041 {
            get {
                return ResourceManager.GetString("str1041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sift_pos に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1042 {
            get {
                return ResourceManager.GetString("str1042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1043 {
            get {
                return ResourceManager.GetString("str1043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   roicaltable_dir に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1044 {
            get {
                return ResourceManager.GetString("str1044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   roical_table に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1045 {
            get {
                return ResourceManager.GetString("str1045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pdtable_dir に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1046 {
            get {
                return ResourceManager.GetString("str1046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pd_table に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1047 {
            get {
                return ResourceManager.GetString("str1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   roical に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1048 {
            get {
                return ResourceManager.GetString("str1048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1049 {
            get {
                return ResourceManager.GetString("str1049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scano_dir に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1050 {
            get {
                return ResourceManager.GetString("str1050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pro_dir に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1051 {
            get {
                return ResourceManager.GetString("str1051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   view_dir に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1052 {
            get {
                return ResourceManager.GetString("str1052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pro_posdir に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1053 {
            get {
                return ResourceManager.GetString("str1053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scano_dispdir に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1054 {
            get {
                return ResourceManager.GetString("str1054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pix_minval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1055 {
            get {
                return ResourceManager.GetString("str1055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pix_maxval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1056 {
            get {
                return ResourceManager.GetString("str1056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ww に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1057 {
            get {
                return ResourceManager.GetString("str1057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1058 {
            get {
                return ResourceManager.GetString("str1058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   graphic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1059 {
            get {
                return ResourceManager.GetString("str1059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rotation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1060 {
            get {
                return ResourceManager.GetString("str1060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   trvsno に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1061 {
            get {
                return ResourceManager.GetString("str1061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   trvspt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1062 {
            get {
                return ResourceManager.GetString("str1062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   realfdd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1063 {
            get {
                return ResourceManager.GetString("str1063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dtpitch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1064 {
            get {
                return ResourceManager.GetString("str1064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fanangle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1065 {
            get {
                return ResourceManager.GetString("str1065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fCD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1066 {
            get {
                return ResourceManager.GetString("str1066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   trpitch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1067 {
            get {
                return ResourceManager.GetString("str1067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tbldia に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1068 {
            get {
                return ResourceManager.GetString("str1068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   aprtpt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1069 {
            get {
                return ResourceManager.GetString("str1069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bias に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1070 {
            get {
                return ResourceManager.GetString("str1070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   slope に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1071 {
            get {
                return ResourceManager.GetString("str1071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mainch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1072 {
            get {
                return ResourceManager.GetString("str1072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   refch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1073 {
            get {
                return ResourceManager.GetString("str1073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dumych に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1074 {
            get {
                return ResourceManager.GetString("str1074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   datach に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1075 {
            get {
                return ResourceManager.GetString("str1075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   allch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1076 {
            get {
                return ResourceManager.GetString("str1076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   offsetapr に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1077 {
            get {
                return ResourceManager.GetString("str1077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   offsetpt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1078 {
            get {
                return ResourceManager.GetString("str1078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   airdtpt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1079 {
            get {
                return ResourceManager.GetString("str1079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   clct_inf に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1080 {
            get {
                return ResourceManager.GetString("str1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scanotvs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1081 {
            get {
                return ResourceManager.GetString("str1081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scanoapr に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1082 {
            get {
                return ResourceManager.GetString("str1082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scanopt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1083 {
            get {
                return ResourceManager.GetString("str1083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scanoscl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1084 {
            get {
                return ResourceManager.GetString("str1084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scanoair に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1085 {
            get {
                return ResourceManager.GetString("str1085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scanobias に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1086 {
            get {
                return ResourceManager.GetString("str1086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scanoslop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1087 {
            get {
                return ResourceManager.GetString("str1087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scanotblbias に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1088 {
            get {
                return ResourceManager.GetString("str1088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scanoudpitch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1089 {
            get {
                return ResourceManager.GetString("str1089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scanodpratio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1090 {
            get {
                return ResourceManager.GetString("str1090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scano_matsiz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1091 {
            get {
                return ResourceManager.GetString("str1091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scan_view に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1092 {
            get {
                return ResourceManager.GetString("str1092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   integ_number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1093 {
            get {
                return ResourceManager.GetString("str1093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   recon_start_angle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1094 {
            get {
                return ResourceManager.GetString("str1094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   image_bias に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1095 {
            get {
                return ResourceManager.GetString("str1095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   image_slope に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1096 {
            get {
                return ResourceManager.GetString("str1096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   image_direction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1097 {
            get {
                return ResourceManager.GetString("str1097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mcenter_channel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1098 {
            get {
                return ResourceManager.GetString("str1098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mchannel_pitch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1099 {
            get {
                return ResourceManager.GetString("str1099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mzoomx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1100 {
            get {
                return ResourceManager.GetString("str1100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mzoomy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1101 {
            get {
                return ResourceManager.GetString("str1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mzoomsize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1102 {
            get {
                return ResourceManager.GetString("str1102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mscan_area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1103 {
            get {
                return ResourceManager.GetString("str1103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   max_mscan_area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1104 {
            get {
                return ResourceManager.GetString("str1104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fimage_bit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1105 {
            get {
                return ResourceManager.GetString("str1105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1106 {
            get {
                return ResourceManager.GetString("str1106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   recon_mask に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1107 {
            get {
                return ResourceManager.GetString("str1107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   n1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1108 {
            get {
                return ResourceManager.GetString("str1108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   n2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1109 {
            get {
                return ResourceManager.GetString("str1109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1110 {
            get {
                return ResourceManager.GetString("str1110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   theta0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1111 {
            get {
                return ResourceManager.GetString("str1111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   theta01 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1112 {
            get {
                return ResourceManager.GetString("str1112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   theta02 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1113 {
            get {
                return ResourceManager.GetString("str1113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   thetaoff に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1114 {
            get {
                return ResourceManager.GetString("str1114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   nc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1115 {
            get {
                return ResourceManager.GetString("str1115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   delta_theta に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1116 {
            get {
                return ResourceManager.GetString("str1116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dpm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1117 {
            get {
                return ResourceManager.GetString("str1117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   n0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1118 {
            get {
                return ResourceManager.GetString("str1118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   m0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1119 {
            get {
                return ResourceManager.GetString("str1119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alpha に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1120 {
            get {
                return ResourceManager.GetString("str1120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1121 {
            get {
                return ResourceManager.GetString("str1121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   zs0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1122 {
            get {
                return ResourceManager.GetString("str1122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Iud に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1123 {
            get {
                return ResourceManager.GetString("str1123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ioff に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1124 {
            get {
                return ResourceManager.GetString("str1124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   K に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1125 {
            get {
                return ResourceManager.GetString("str1125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   delta_z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1126 {
            get {
                return ResourceManager.GetString("str1126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ze0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1127 {
            get {
                return ResourceManager.GetString("str1127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   inh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1128 {
            get {
                return ResourceManager.GetString("str1128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   md に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1129 {
            get {
                return ResourceManager.GetString("str1129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   B1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1130 {
            get {
                return ResourceManager.GetString("str1130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scan_posi_a に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1131 {
            get {
                return ResourceManager.GetString("str1131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   multi_tube に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1132 {
            get {
                return ResourceManager.GetString("str1132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Z0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1133 {
            get {
                return ResourceManager.GetString("str1133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   acq_view に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1134 {
            get {
                return ResourceManager.GetString("str1134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fid_offset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1135 {
            get {
                return ResourceManager.GetString("str1135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fcd_offset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1136 {
            get {
                return ResourceManager.GetString("str1136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1137 {
            get {
                return ResourceManager.GetString("str1137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1138 {
            get {
                return ResourceManager.GetString("str1138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1139 {
            get {
                return ResourceManager.GetString("str1139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1140 {
            get {
                return ResourceManager.GetString("str1140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1141 {
            get {
                return ResourceManager.GetString("str1141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1142 {
            get {
                return ResourceManager.GetString("str1142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1143 {
            get {
                return ResourceManager.GetString("str1143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   instance_num に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1144 {
            get {
                return ResourceManager.GetString("str1144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iifield に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1145 {
            get {
                return ResourceManager.GetString("str1145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1146 {
            get {
                return ResourceManager.GetString("str1146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   study_id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1147 {
            get {
                return ResourceManager.GetString("str1147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   series_num に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1148 {
            get {
                return ResourceManager.GetString("str1148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   acq_num に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1149 {
            get {
                return ResourceManager.GetString("str1149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   instance_uid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1150 {
            get {
                return ResourceManager.GetString("str1150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   frame_rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1151 {
            get {
                return ResourceManager.GetString("str1151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scan_start_angle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1152 {
            get {
                return ResourceManager.GetString("str1152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   detector に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1153 {
            get {
                return ResourceManager.GetString("str1153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   data_mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1154 {
            get {
                return ResourceManager.GetString("str1154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cone_image_mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1155 {
            get {
                return ResourceManager.GetString("str1155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fine_table_x に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1156 {
            get {
                return ResourceManager.GetString("str1156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ftable_x_pos に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1157 {
            get {
                return ResourceManager.GetString("str1157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fine_table_y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1158 {
            get {
                return ResourceManager.GetString("str1158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ftable_y_pos に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1159 {
            get {
                return ResourceManager.GetString("str1159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rotate_select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1160 {
            get {
                return ResourceManager.GetString("str1160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   c_cw_ccw に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1161 {
            get {
                return ResourceManager.GetString("str1161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1162 {
            get {
                return ResourceManager.GetString("str1162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   airLogValue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1163 {
            get {
                return ResourceManager.GetString("str1163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fpd_gain_f に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1164 {
            get {
                return ResourceManager.GetString("str1164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fpd_integ_f に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1165 {
            get {
                return ResourceManager.GetString("str1165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   xfilter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1166 {
            get {
                return ResourceManager.GetString("str1166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   xfilter_c に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1167 {
            get {
                return ResourceManager.GetString("str1167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   xfocus に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1168 {
            get {
                return ResourceManager.GetString("str1168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   xfocus_c に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1169 {
            get {
                return ResourceManager.GetString("str1169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   largeRotTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1170 {
            get {
                return ResourceManager.GetString("str1170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   table_rotation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1171 {
            get {
                return ResourceManager.GetString("str1171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   auto_centering に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1172 {
            get {
                return ResourceManager.GetString("str1172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mscano_area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1173 {
            get {
                return ResourceManager.GetString("str1173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mscano_mdtpitch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1174 {
            get {
                return ResourceManager.GetString("str1174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mscano_width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1175 {
            get {
                return ResourceManager.GetString("str1175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mscanopt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1176 {
            get {
                return ResourceManager.GetString("str1176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mscanoscl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1177 {
            get {
                return ResourceManager.GetString("str1177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mscano_udpitch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1178 {
            get {
                return ResourceManager.GetString("str1178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mscano_bias に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1179 {
            get {
                return ResourceManager.GetString("str1179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mscano_slope に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1180 {
            get {
                return ResourceManager.GetString("str1180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mscano_dp_ratio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1181 {
            get {
                return ResourceManager.GetString("str1181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   numOfAdjCenterCh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1182 {
            get {
                return ResourceManager.GetString("str1182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scan_fcdMecha に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1183 {
            get {
                return ResourceManager.GetString("str1183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scan_fcdLinear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1184 {
            get {
                return ResourceManager.GetString("str1184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scan_fddMecha に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1185 {
            get {
                return ResourceManager.GetString("str1185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scan_fddLinear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1186 {
            get {
                return ResourceManager.GetString("str1186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scan_table_x_posMecha に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1187 {
            get {
                return ResourceManager.GetString("str1187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scan_table_x_posLinear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1188 {
            get {
                return ResourceManager.GetString("str1188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scan_udab_pos に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1189 {
            get {
                return ResourceManager.GetString("str1189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   scan_ud_linear_pos に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1190 {
            get {
                return ResourceManager.GetString("str1190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   w_scan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1191 {
            get {
                return ResourceManager.GetString("str1191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pl_mbhc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1192 {
            get {
                return ResourceManager.GetString("str1192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pl_collion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1193 {
            get {
                return ResourceManager.GetString("str1193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pl_mbhc_mat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1194 {
            get {
                return ResourceManager.GetString("str1194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pl_mbhc_para に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1195 {
            get {
                return ResourceManager.GetString("str1195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1196 {
            get {
                return ResourceManager.GetString("str1196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1197 {
            get {
                return ResourceManager.GetString("str1197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1198 {
            get {
                return ResourceManager.GetString("str1198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1199 {
            get {
                return ResourceManager.GetString("str1199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1200 {
            get {
                return ResourceManager.GetString("str1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1201 {
            get {
                return ResourceManager.GetString("str1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1202 {
            get {
                return ResourceManager.GetString("str1202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1203 {
            get {
                return ResourceManager.GetString("str1203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1204 {
            get {
                return ResourceManager.GetString("str1204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1205 {
            get {
                return ResourceManager.GetString("str1205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1206 {
            get {
                return ResourceManager.GetString("str1206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1207 {
            get {
                return ResourceManager.GetString("str1207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1208 {
            get {
                return ResourceManager.GetString("str1208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1209 {
            get {
                return ResourceManager.GetString("str1209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1210 {
            get {
                return ResourceManager.GetString("str1210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1211 {
            get {
                return ResourceManager.GetString("str1211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1212 {
            get {
                return ResourceManager.GetString("str1212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1213 {
            get {
                return ResourceManager.GetString("str1213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1214 {
            get {
                return ResourceManager.GetString("str1214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1215 {
            get {
                return ResourceManager.GetString("str1215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1216 {
            get {
                return ResourceManager.GetString("str1216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1217 {
            get {
                return ResourceManager.GetString("str1217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1218 {
            get {
                return ResourceManager.GetString("str1218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1219 {
            get {
                return ResourceManager.GetString("str1219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str1220 {
            get {
                return ResourceManager.GetString("str1220", resourceCulture);
            }
        }
    }
}
