//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DioLib.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DioLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _DI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DI_NAME_SUFFIX {
            get {
                return ResourceManager.GetString("DI_NAME_SUFFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FBIDIO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIO_NAME_HEADER {
            get {
                return ResourceManager.GetString("DIO_NAME_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _DO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DO_NAME_SUFFIX {
            get {
                return ResourceManager.GetString("DO_NAME_SUFFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;The device has already been opened.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_ALREADY_OPEN {
            get {
                return ResourceManager.GetString("ERROR_ALREADY_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_DIOLIB {
            get {
                return ResourceManager.GetString("ERROR_DIOLIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;Failed to call the driver.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_DRVCAL {
            get {
                return ResourceManager.GetString("ERROR_DRVCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;End of file is reached&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_HANDLE_EOF {
            get {
                return ResourceManager.GetString("ERROR_HANDLE_EOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;The data area passed to the system call is too small.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_INSUFFICIENT_BUFFER {
            get {
                return ResourceManager.GetString("ERROR_INSUFFICIENT_BUFFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;Invalid function is called.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_INVALID_CALL {
            get {
                return ResourceManager.GetString("ERROR_INVALID_CALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;The device handle is invalid.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_INVALID_HANDLE {
            get {
                return ResourceManager.GetString("ERROR_INVALID_HANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;I/O event is not signaled asynchronously.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_IO_INCOMPLETE {
            get {
                return ResourceManager.GetString("ERROR_IO_INCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;Overlapped I/O operations are in progress.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_IO_PENDING {
            get {
                return ResourceManager.GetString("ERROR_IO_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;Not enough memory.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_MEMORY_NOTALLOCATED {
            get {
                return ResourceManager.GetString("ERROR_MEMORY_NOTALLOCATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;More available data exists.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_MORE_DATA {
            get {
                return ResourceManager.GetString("ERROR_MORE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;The specified driver cannot be called.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_NOT_DEVICE {
            get {
                return ResourceManager.GetString("ERROR_NOT_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;The specified driver cannot be called.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_NOT_OPEN {
            get {
                return ResourceManager.GetString("ERROR_NOT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;The specified function is not supported.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("ERROR_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;A NULL pointer is passed between the driver and the DLL.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_NULL_POINTER {
            get {
                return ResourceManager.GetString("ERROR_NULL_POINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;The specified parameter is invalid.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_PARAMETER {
            get {
                return ResourceManager.GetString("ERROR_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;The process was successfully completed.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_SUCCESS {
            get {
                return ResourceManager.GetString("ERROR_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;[{0}] is an unknown error code.&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_UNKNOWN {
            get {
                return ResourceManager.GetString("ERROR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;Error Unsafe Use&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_UNSAFE_USE {
            get {
                return ResourceManager.GetString("ERROR_UNSAFE_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Mutex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MUTEX_NAME_SUFFIX {
            get {
                return ResourceManager.GetString("MUTEX_NAME_SUFFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SHARED_MEMORY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SHARED_NAME {
            get {
                return ResourceManager.GetString("SHARED_NAME", resourceCulture);
            }
        }
    }
}
