//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Board.BoardControl {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BoardMes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BoardMes() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Board.BoardControl.BoardMes", typeof(BoardMes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   制御ボードを閉じるときにエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BOARD_CLOSE_ERROR {
            get {
                return ResourceManager.GetString("BOARD_CLOSE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制御ボード接続時にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BOARD_CONNECTION_ERROR {
            get {
                return ResourceManager.GetString("BOARD_CONNECTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制御ボード監視中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BOARD_ERROR {
            get {
                return ResourceManager.GetString("BOARD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -XELS入力ONによる停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BOARD_ERROR_M_XELS {
            get {
                return ResourceManager.GetString("BOARD_ERROR_M_XELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +XELS入力ONによる停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BOARD_ERROR_P_XELS {
            get {
                return ResourceManager.GetString("BOARD_ERROR_P_XELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定速に達しませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BOARD_ERROR_SPEED {
            get {
                return ResourceManager.GetString("BOARD_ERROR_SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XSVALM入力ONによる停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BOARD_ERROR_XSVALM {
            get {
                return ResourceManager.GetString("BOARD_ERROR_XSVALM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   msec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BOARD_SEC {
            get {
                return ResourceManager.GetString("BOARD_SEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制御ボードを確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIRM_BOARD {
            get {
                return ResourceManager.GetString("CONFIRM_BOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装置内部を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIRM_ENCLOSUER {
            get {
                return ResourceManager.GetString("CONFIRM_ENCLOSUER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実際に動いてるか確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIRM_OPERATION {
            get {
                return ResourceManager.GetString("CONFIRM_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制御ボードを開くことができませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_OPEN {
            get {
                return ResourceManager.GetString("ERROR_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   例外エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXCEPTION_ERROR {
            get {
                return ResourceManager.GetString("EXCEPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   \r\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INDENTION {
            get {
                return ResourceManager.GetString("INDENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションを再立ち上げしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string REBOOT_APP {
            get {
                return ResourceManager.GetString("REBOOT_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイムアウトエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMEOUT_ERROR {
            get {
                return ResourceManager.GetString("TIMEOUT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制御ボードを検出できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UNDETECT_BOARD {
            get {
                return ResourceManager.GetString("UNDETECT_BOARD", resourceCulture);
            }
        }
    }
}
