//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Board.BoardControl {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class BoardParam : global::System.Configuration.ApplicationSettingsBase {
        
        private static BoardParam defaultInstance = ((BoardParam)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BoardParam())));
        
        public static BoardParam Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint RotCount {
            get {
                return ((uint)(this["RotCount"]));
            }
            set {
                this["RotCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint RotEncoderCount {
            get {
                return ((uint)(this["RotEncoderCount"]));
            }
            set {
                this["RotEncoderCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float RotDisp {
            get {
                return ((float)(this["RotDisp"]));
            }
            set {
                this["RotDisp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint UdPosCount {
            get {
                return ((uint)(this["UdPosCount"]));
            }
            set {
                this["UdPosCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint UdCount {
            get {
                return ((uint)(this["UdCount"]));
            }
            set {
                this["UdCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint UdEncoderCount {
            get {
                return ((uint)(this["UdEncoderCount"]));
            }
            set {
                this["UdEncoderCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint XStgCount {
            get {
                return ((uint)(this["XStgCount"]));
            }
            set {
                this["XStgCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint XStgEncoderCount {
            get {
                return ((uint)(this["XStgEncoderCount"]));
            }
            set {
                this["XStgEncoderCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint YStgCount {
            get {
                return ((uint)(this["YStgCount"]));
            }
            set {
                this["YStgCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint YStgEncoderCount {
            get {
                return ((uint)(this["YStgEncoderCount"]));
            }
            set {
                this["YStgEncoderCount"] = value;
            }
        }
    }
}
