//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.296
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT30K.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CT30K.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ＣＴプログラムが既に実行されていますので、先に立上がっている方を使用してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_09349 {
            get {
                return ResourceManager.GetString("Msg_09349", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_09913 {
            get {
                return ResourceManager.GetString("Msg_09913", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}軸 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_12160 {
            get {
                return ResourceManager.GetString("Msg_12160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}と{1}がともに有効なため、CT30Kを起動できません。
        ///どちらかを無効にするように設定ファイル scaninhibit.csv を修正した後、CT30Kを再起動してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_17486 {
            get {
                return ResourceManager.GetString("Msg_17486", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X線管回転 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_17487 {
            get {
                return ResourceManager.GetString("Msg_17487", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高速度透視撮影 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_17488 {
            get {
                return ResourceManager.GetString("Msg_17488", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複数X線管 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_17489 {
            get {
                return ResourceManager.GetString("Msg_17489", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回転選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_17490 {
            get {
                return ResourceManager.GetString("Msg_17490", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下のファイルが見つかりません。CT30Kを終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_20181 {
            get {
                return ResourceManager.GetString("Msg_20181", resourceCulture);
            }
        }
    }
}
