//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechaMaintCnt.Selector {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class SelCont : global::System.Configuration.ApplicationSettingsBase {
        
        private static SelCont defaultInstance = ((SelCont)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SelCont())));
        
        public static SelCont Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FCD")]
        public string SelContent {
            get {
                return ((string)(this["SelContent"]));
            }
            set {
                this["SelContent"] = value;
            }
        }
    }
}
