//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TXSMechaControl {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MechaRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MechaRes() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TXSMechaControl.MechaRes", typeof(MechaRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   接触あり に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COLITION {
            get {
                return ResourceManager.GetString("COLITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   装置内部を確認してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIRM_OPERATION {
            get {
                return ResourceManager.GetString("CONFIRM_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXCEPTION_ERROR {
            get {
                return ResourceManager.GetString("EXCEPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インデックス動作中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INDEX_Process {
            get {
                return ResourceManager.GetString("INDEX_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大型テーブルモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LARGE_TABLE_MODE {
            get {
                return ResourceManager.GetString("LARGE_TABLE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ON_MOVE {
            get {
                return ResourceManager.GetString("ON_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   停止中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ON_STOP {
            get {
                return ResourceManager.GetString("ON_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PROCESS_COMPLEAT {
            get {
                return ResourceManager.GetString("PROCESS_COMPLEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   停止しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PROCESS_STOP {
            get {
                return ResourceManager.GetString("PROCESS_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リセット中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RESET_Process {
            get {
                return ResourceManager.GetString("RESET_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [H]:高速 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SPD_H {
            get {
                return ResourceManager.GetString("SPD_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [L]:低速 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SPD_L {
            get {
                return ResourceManager.GetString("SPD_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [M]:中速 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SPD_M {
            get {
                return ResourceManager.GetString("SPD_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [SL]:超低速 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SPD_SL {
            get {
                return ResourceManager.GetString("SPD_SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スピードを設定できませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SPEED_SET_ERROR {
            get {
                return ResourceManager.GetString("SPEED_SET_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイムアウトエラーが発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TIMEOUT_ERROR {
            get {
                return ResourceManager.GetString("TIMEOUT_ERROR", resourceCulture);
            }
        }
    }
}
